In [1]:
# The first step in data cleaning is to import all libraries needed:

import re
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import argparse
import datetime
import requests
from lxml import html
import lxml.html as lh
from bs4 import BeautifulSoup
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv('df_to_clean')
display(df)

,Unnamed: 0,id,Unnamed: 0_x,Source,worth,worthChange,realTimeWorth,realTimePosition,lastName,age,Unnamed: 0_y,gender,country,image,name,position,Unnamed: 0.1
0,0,9478,52,Technology ==> Amazon,112.0 BUSD,0.0 millions USD,NaN,1,beZOS,54 years old,52,M,United States,https://specials-images.forbesimg.com/imageser...,JEFF BEZOS,1.0,52
1,1,4608,53,Technology ==> Microsoft,90.0 BUSD,-0.001 millions USD,NaN,2,GATES,62 years old,53,M,United States,https://specials-images.forbesimg.com/imageser...,BILL GATEs,2.0,53
2,2,8790,54,Finance and Investments ==> Berkshire Hathaway,84.0 BUSD,-0.002 millions USD,NaN,3,bufFEtt,87 years old,54,None,None,https://specials-images.forbesimg.com/imageser...,warren BUffett,3.0,54
3,3,1463,55,Fashion & Retail ==> LVMH,72.0 BUSD,0.0 millions USD,NaN,4,aRNAULt,69 years old,55,None,None,https://specials-images.forbesimg.com/imageser...,beRNARD ARNAUlt,4.0,55
4,4,3517,56,Technology ==> Facebook,71.0 BUSD,0.0 millions USD,NaN,5,zuckERBErg,1985,56,Male,United States,https://specials-images.forbesimg.com/imageser...,mARK ZUCKERBErg,5.0,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2203,4826,2255,"Fashion & Retail ==> fashion, entertainment",1.0 BUSD,0.0 millions USD,NaN,2134,zHAO,51 years old,2255,Male,China,https://specials-images.forbesimg.com/imageser...,zhao XIAOQiang,2204.0,2255
2204,2204,8947,2256,Manufacturing ==> electrical equipment,1.0 BUSD,nan millions USD,NaN,2134,zhOU,55 years old,2256,None,None,https://specials-images.forbesimg.com/imageser...,zhou LIANGzhang,2205.0,2256
2205,2205,5744,2257,Manufacturing ==> electrical equipment,1.0 BUSD,0.0 millions USD,NaN,1856,zHU,51 years old,2257,M,None,https://specials-images.forbesimg.com/imageser...,zHU XINGMING,2206.0,2257
2206,2206,6586,2258,Manufacturing ==> printed circuit boards,1.0 BUSD,0.0 millions USD,NaN,1978,zHUO,52 years old,2258,F,Hong Kong,https://specials-images.forbesimg.com/imageser...,ZHUO JUn,2207.0,2258
2207,2207,9507,2259,Diversified ==> diversified,1.0 BUSD,nan millions USD,NaN,1978,zORLU,54 years old,2259,M,Turkey,https://specials-images.forbesimg.com/imageser...,olgun ZORLu,2208.0,2259

In [3]:
df[['work_field', 'company']] = df.Source.str.split(' ==> ', expand=True)
df

,Unnamed: 0,id,Unnamed: 0_x,Source,worth,worthChange,realTimeWorth,realTimePosition,lastName,age,Unnamed: 0_y,gender,country,image,name,position,Unnamed: 0.1,work_field,company
0,0,9478,52,Technology ==> Amazon,112.0 BUSD,0.0 millions USD,NaN,1,beZOS,54 years old,52,M,United States,https://specials-images.forbesimg.com/imageser...,JEFF BEZOS,1.0,52,Technology,Amazon
1,1,4608,53,Technology ==> Microsoft,90.0 BUSD,-0.001 millions USD,NaN,2,GATES,62 years old,53,M,United States,https://specials-images.forbesimg.com/imageser...,BILL GATEs,2.0,53,Technology,Microsoft
2,2,8790,54,Finance and Investments ==> Berkshire Hathaway,84.0 BUSD,-0.002 millions USD,NaN,3,bufFEtt,87 years old,54,None,None,https://specials-images.forbesimg.com/imageser...,warren BUffett,3.0,54,Finance and Investments,Berkshire Hathaway
3,3,1463,55,Fashion & Retail ==> LVMH,72.0 BUSD,0.0 millions USD,NaN,4,aRNAULt,69 years old,55,None,None,https://specials-images.forbesimg.com/imageser...,beRNARD ARNAUlt,4.0,55,Fashion & Retail,LVMH
4,4,3517,56,Technology ==> Facebook,71.0 BUSD,0.0 millions USD,NaN,5,zuckERBErg,1985,56,Male,United States,https://specials-images.forbesimg.com/imageser...,mARK ZUCKERBErg,5.0,56,Technology,Facebook
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2203,4826,2255,"Fashion & Retail ==> fashion, entertainment",1.0 BUSD,0.0 millions USD,NaN,2134,zHAO,51 years old,2255,Male,China,https://specials-images.forbesimg.com/imageser...,zhao XIAOQiang,2204.0,2255,Fashion & Retail,"fashion, entertainment"
2204,2204,8947,2256,Manufacturing ==> electrical equipment,1.0 BUSD,nan millions USD,NaN,2134,zhOU,55 years old,2256,None,None,https://specials-images.forbesimg.com/imageser...,zhou LIANGzhang,2205.0,2256,Manufacturing,electrical equipment
2205,2205,5744,2257,Manufacturing ==> electrical equipment,1.0 BUSD,0.0 millions USD,NaN,1856,zHU,51 years old,2257,M,None,https://specials-images.forbesimg.com/imageser...,zHU XINGMING,2206.0,2257,Manufacturing,electrical equipment
2206,2206,6586,2258,Manufacturing ==> printed circuit boards,1.0 BUSD,0.0 millions USD,NaN,1978,zHUO,52 years old,2258,F,Hong Kong,https://specials-images.forbesimg.com/imageser...,ZHUO JUn,2207.0,2258,Manufacturing,printed circuit boards
2207,2207,9507,2259,Diversified ==> diversified,1.0 BUSD,nan millions USD,NaN,1978,zORLU,54 years old,2259,M,Turkey,https://specials-images.forbesimg.com/imageser...,olgun ZORLu,2208.0,2259,Diversified,diversified

In [4]:
def drop_cols(lst):
    for i in lst:
        df.drop(i, axis=1, inplace=True)

In [5]:
cols_to_drop=['Unnamed: 0', 'id', 'Unnamed: 0_x', 'realTimeWorth', 'Unnamed: 0_y', 'Unnamed: 0.1', 'Source']
drop_cols(cols_to_drop)

In [6]:
clean_text = {'worth': ' BUSD', 'worthChange': ' millions USD', 'age': ' years old'}
def clean_numcols_from_text(dic):
    for k, v in dic.items():
        df[k] = df[k].str.replace(v, '')
clean_numcols_from_text(clean_text)

In [7]:
def column_title(df, ls):
    for i in ls:
        df.update(df[i].str.title())
    return df
ls_cols = ['name', 'lastName', 'company']
column_title(df, ls_cols)

,worth,worthChange,realTimePosition,lastName,age,gender,country,image,name,position,work_field,company
0,112.0,0.0,1,Bezos,54,M,United States,https://specials-images.forbesimg.com/imageser...,Jeff Bezos,1.0,Technology,Amazon
1,90.0,-0.001,2,Gates,62,M,United States,https://specials-images.forbesimg.com/imageser...,Bill Gates,2.0,Technology,Microsoft
2,84.0,-0.002,3,Buffett,87,None,None,https://specials-images.forbesimg.com/imageser...,Warren Buffett,3.0,Finance and Investments,Berkshire Hathaway
3,72.0,0.0,4,Arnault,69,None,None,https://specials-images.forbesimg.com/imageser...,Bernard Arnault,4.0,Fashion & Retail,Lvmh
4,71.0,0.0,5,Zuckerberg,1985,Male,United States,https://specials-images.forbesimg.com/imageser...,Mark Zuckerberg,5.0,Technology,Facebook
...,...,...,...,...,...,...,...,...,...,...,...,...
2203,1.0,0.0,2134,Zhao,51,Male,China,https://specials-images.forbesimg.com/imageser...,Zhao Xiaoqiang,2204.0,Fashion & Retail,"Fashion, Entertainment"
2204,1.0,nan,2134,Zhou,55,None,None,https://specials-images.forbesimg.com/imageser...,Zhou Liangzhang,2205.0,Manufacturing,Electrical Equipment
2205,1.0,0.0,1856,Zhu,51,M,None,https://specials-images.forbesimg.com/imageser...,Zhu Xingming,2206.0,Manufacturing,Electrical Equipment
2206,1.0,0.0,1978,Zhuo,52,F,Hong Kong,https://specials-images.forbesimg.com/imageser...,Zhuo Jun,2207.0,Manufacturing,Printed Circuit Boards
2207,1.0,nan,1978,Zorlu,54,M,Turkey,https://specials-images.forbesimg.com/imageser...,Olgun Zorlu,2208.0,Diversified,Diversified

In [8]:
df = df.rename(columns={'name': 'first_name', 'lastName': 'last_name', 'realTimePosition': \
                        'real_time_position', 'worth': 'worth(BUSD)', 'worthChange': 'worth(millions_USD)'})
df = df[['position', 'first_name', 'last_name', 'age', 'gender', 'country', 'real_time_position', \
              'worth(BUSD)', 'worth(millions_USD)', 'work_field', 'company', 'image']]

display(df)

,position,first_name,last_name,age,gender,country,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image
0,1.0,Jeff Bezos,Bezos,54,M,United States,1,112.0,0.0,Technology,Amazon,https://specials-images.forbesimg.com/imageser...
1,2.0,Bill Gates,Gates,62,M,United States,2,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...
2,3.0,Warren Buffett,Buffett,87,None,None,3,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...
3,4.0,Bernard Arnault,Arnault,69,None,None,4,72.0,0.0,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...
4,5.0,Mark Zuckerberg,Zuckerberg,1985,Male,United States,5,71.0,0.0,Technology,Facebook,https://specials-images.forbesimg.com/imageser...
...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2204.0,Zhao Xiaoqiang,Zhao,51,Male,China,2134,1.0,0.0,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...
2204,2205.0,Zhou Liangzhang,Zhou,55,None,None,2134,1.0,nan,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2205,2206.0,Zhu Xingming,Zhu,51,M,None,1856,1.0,0.0,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2206,2207.0,Zhuo Jun,Zhuo,52,F,Hong Kong,1978,1.0,0.0,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...
2207,2208.0,Olgun Zorlu,Zorlu,54,M,Turkey,1978,1.0,nan,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...

In [9]:
# Since we had the first and last name in the column name, with the following code we have only the first
# name in the column name and the last name in the column lastName
df['first_name'] = [a.replace(b, '').strip() for a, b in zip(df['first_name'], df['last_name'])]

display(df)

,position,first_name,last_name,age,gender,country,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image
0,1.0,Jeff,Bezos,54,M,United States,1,112.0,0.0,Technology,Amazon,https://specials-images.forbesimg.com/imageser...
1,2.0,Bill,Gates,62,M,United States,2,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...
2,3.0,Warren,Buffett,87,None,None,3,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...
3,4.0,Bernard,Arnault,69,None,None,4,72.0,0.0,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...
4,5.0,Mark,Zuckerberg,1985,Male,United States,5,71.0,0.0,Technology,Facebook,https://specials-images.forbesimg.com/imageser...
...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2204.0,Xiaoqiang,Zhao,51,Male,China,2134,1.0,0.0,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...
2204,2205.0,Liangzhang,Zhou,55,None,None,2134,1.0,nan,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2205,2206.0,Xingming,Zhu,51,M,None,1856,1.0,0.0,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2206,2207.0,Jun,Zhuo,52,F,Hong Kong,1978,1.0,0.0,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...
2207,2208.0,Olgun,Zorlu,54,M,Turkey,1978,1.0,nan,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...

In [10]:
# This command is necessary to check the values we have in this series:
df['gender'].value_counts()

M         1127
None       495
Male       382
F          155
Female      36
Name: gender, dtype: int64

In [11]:
df.gender.replace('Male', 'M', inplace=True)
df.gender.replace('Female', 'F', inplace=True)
display(df)

,position,first_name,last_name,age,gender,country,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image
0,1.0,Jeff,Bezos,54,M,United States,1,112.0,0.0,Technology,Amazon,https://specials-images.forbesimg.com/imageser...
1,2.0,Bill,Gates,62,M,United States,2,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...
2,3.0,Warren,Buffett,87,None,None,3,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...
3,4.0,Bernard,Arnault,69,None,None,4,72.0,0.0,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...
4,5.0,Mark,Zuckerberg,1985,M,United States,5,71.0,0.0,Technology,Facebook,https://specials-images.forbesimg.com/imageser...
...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2204.0,Xiaoqiang,Zhao,51,M,China,2134,1.0,0.0,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...
2204,2205.0,Liangzhang,Zhou,55,None,None,2134,1.0,nan,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2205,2206.0,Xingming,Zhu,51,M,None,1856,1.0,0.0,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2206,2207.0,Jun,Zhuo,52,F,Hong Kong,1978,1.0,0.0,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...
2207,2208.0,Olgun,Zorlu,54,M,Turkey,1978,1.0,nan,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...

In [12]:
# Transform all ages to correct numbers:
df.age.fillna(str(-2019), inplace=True)
current_year = datetime.datetime.today().year

age = []
for i in df['age']:
    if len(str(i)) == 4:
        age.append(str(current_year-int(i)))
    else:
         age.append(i)

df['age'] = age
display(df)

,position,first_name,last_name,age,gender,country,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image
0,1.0,Jeff,Bezos,54,M,United States,1,112.0,0.0,Technology,Amazon,https://specials-images.forbesimg.com/imageser...
1,2.0,Bill,Gates,62,M,United States,2,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...
2,3.0,Warren,Buffett,87,None,None,3,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...
3,4.0,Bernard,Arnault,69,None,None,4,72.0,0.0,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...
4,5.0,Mark,Zuckerberg,35,M,United States,5,71.0,0.0,Technology,Facebook,https://specials-images.forbesimg.com/imageser...
...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2204.0,Xiaoqiang,Zhao,51,M,China,2134,1.0,0.0,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...
2204,2205.0,Liangzhang,Zhou,55,None,None,2134,1.0,nan,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2205,2206.0,Xingming,Zhu,51,M,None,1856,1.0,0.0,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2206,2207.0,Jun,Zhuo,52,F,Hong Kong,1978,1.0,0.0,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...
2207,2208.0,Olgun,Zorlu,54,M,Turkey,1978,1.0,nan,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...

In [13]:
# The function change_types receives a list of columns of the df as an argument and will convert its type
# to float, so it's possible to operate with them.
def change_to_float_type(l):
    for i in l:
        df[i] = df[i].astype(float)
change_to_float_type(['worth(BUSD)', 'worth(millions_USD)'])

In [14]:
# To complete our data I had to get this file:
path = '../data/raw/forbes_2018.csv'
forbes = pd.read_csv(path)
forbes.tail(15)

,position,name,lastName,age,country,gender,wealthSource,industry,worth,worthChange,realTimeWorth,realTimePosition,image
2245,2194.0,Surin Upatkoon,Upatkoon,69.0,Thailand,M,"telecom, lotteries, insurance",Diversified,1000.0,0.0,NaN,2100,https://specials-images.forbesimg.com/imageser...
2246,2195.0,Alexander Vik,Vik,63.0,Norway,M,investments,Finance and Investments,1000.0,0.0,NaN,2146,https://specials-images.forbesimg.com/imageser...
2247,2196.0,Peter-Alexander Wacker,Wacker,66.0,Germany,M,chemicals,Manufacturing,1000.0,NaN,NaN,2146,https://specials-images.forbesimg.com/imageser...
2248,2197.0,Wang Jianyi,Wang,55.0,China,M,fiber optic cables,Technology,1000.0,NaN,NaN,2146,https://specials-images.forbesimg.com/imageser...
2249,2198.0,V. Prem Watsa,Watsa,67.0,Canada,M,"insurance, investments",Finance and Investments,1000.0,0.0,NaN,1982,https://specials-images.forbesimg.com/imageser...
2250,2199.0,Sandy Weill,Weill,85.0,United States,M,Citigroup,Finance and Investments,1000.0,0.0,NaN,2144,https://specials-images.forbesimg.com/imageser...
2251,2200.0,Wen Pengcheng,Wen,55.0,China,M,agribusiness,Food and Beverage,1000.0,NaN,NaN,2144,https://specials-images.forbesimg.com/imageser...
2252,2201.0,Wu Chung-yi,Wu,59.0,Taiwan,M,manufacturing,Manufacturing,1000.0,0.0,NaN,2120,https://specials-images.forbesimg.com/imageser...
2253,2202.0,Yang Jianxin,Yang,49.0,China,M,apparel,Technology,1000.0,NaN,NaN,2120,https://specials-images.forbesimg.com/imageser...
2254,2203.0,Yao Xinyi,Yao,53.0,China,M,air conditioning,Diversified,1000.0,0.0,NaN,2114,https://specials-images.forbesimg.com/imageser...
2255,2204.0,Zhao Xiaoqiang,Zhao,51.0,China,M,"fashion, entertainment",Fashion & Retail,1000.0,0.0,NaN,2134,https://specials-images.forbesimg.com/imageser...
2256,2205.0,Zhou Liangzhang,Zhou,55.0,China,M,electrical equipment,Manufacturing,1000.0,NaN,NaN,2134,https://specials-images.forbesimg.com/imageser...
2257,2206.0,Zhu Xingming,Zhu,51.0,China,M,electrical equipment,Manufacturing,1000.0,0.0,NaN,1856,https://specials-images.forbesimg.com/imageser...
2258,2207.0,Zhuo Jun,Zhuo,52.0,Hong Kong,F,printed circuit boards,Manufacturing,1000.0,0.0,NaN,1978,https://specials-images.forbesimg.com/imageser...
2259,2208.0,Olgun Zorlu,Zorlu,54.0,Turkey,M,diversified,Diversified,1000.0,NaN,NaN,1978,https://specials-images.forbesimg.com/imageser...

In [15]:
forbes.dropna(subset=['position'], inplace=True)

forbes.age.isnull().sum()

65

In [16]:
df['gender'] = df['position'].map(forbes.set_index('position')['gender'])
df['country'] = df['position'].map(forbes.set_index('position')['country'])

In [17]:
# Since names from china were wrong
count=-1
df['change_name'] = np.nan
for i in df['country']:
    count+=1
    if i == 'China':
        df['change_name'][count]=df['last_name'][count]
        df['last_name'][count]=df['first_name'][count]
        df['first_name'][count] = df['change_name'][count]
    else:
        pass

In [18]:
df.drop('change_name', axis=1, inplace=True)
display(df)

,position,first_name,last_name,age,gender,country,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image
0,1.0,Jeff,Bezos,54,M,United States,1,112.0,0.000,Technology,Amazon,https://specials-images.forbesimg.com/imageser...
1,2.0,Bill,Gates,62,M,United States,2,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...
2,3.0,Warren,Buffett,87,M,United States,3,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...
3,4.0,Bernard,Arnault,69,M,France,4,72.0,0.000,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...
4,5.0,Mark,Zuckerberg,35,M,United States,5,71.0,0.000,Technology,Facebook,https://specials-images.forbesimg.com/imageser...
...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2204.0,Zhao,Xiaoqiang,51,M,China,2134,1.0,0.000,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...
2204,2205.0,Zhou,Liangzhang,55,M,China,2134,1.0,NaN,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2205,2206.0,Zhu,Xingming,51,M,China,1856,1.0,0.000,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...
2206,2207.0,Jun,Zhuo,52,F,Hong Kong,1978,1.0,0.000,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...
2207,2208.0,Olgun,Zorlu,54,M,Turkey,1978,1.0,NaN,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...

In [19]:
# The column 'name' is going to be used for wikipedia web scraping and the column education is going to be updated
# by the scraped data.
df['name'] = df['first_name'] + '_' + df['last_name']
df['education'] = 'None'

In [20]:
display(df)

,position,first_name,last_name,age,gender,country,real_time_position,worth(BUSD),worth(millions_USD),work_field,company,image,name,education
0,1.0,Jeff,Bezos,54,M,United States,1,112.0,0.000,Technology,Amazon,https://specials-images.forbesimg.com/imageser...,Jeff_Bezos,None
1,2.0,Bill,Gates,62,M,United States,2,90.0,-0.001,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...,Bill_Gates,None
2,3.0,Warren,Buffett,87,M,United States,3,84.0,-0.002,Finance and Investments,Berkshire Hathaway,https://specials-images.forbesimg.com/imageser...,Warren_Buffett,None
3,4.0,Bernard,Arnault,69,M,France,4,72.0,0.000,Fashion & Retail,Lvmh,https://specials-images.forbesimg.com/imageser...,Bernard_Arnault,None
4,5.0,Mark,Zuckerberg,35,M,United States,5,71.0,0.000,Technology,Facebook,https://specials-images.forbesimg.com/imageser...,Mark_Zuckerberg,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2203,2204.0,Zhao,Xiaoqiang,51,M,China,2134,1.0,0.000,Fashion & Retail,"Fashion, Entertainment",https://specials-images.forbesimg.com/imageser...,Zhao_Xiaoqiang,None
2204,2205.0,Zhou,Liangzhang,55,M,China,2134,1.0,NaN,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...,Zhou_Liangzhang,None
2205,2206.0,Zhu,Xingming,51,M,China,1856,1.0,0.000,Manufacturing,Electrical Equipment,https://specials-images.forbesimg.com/imageser...,Zhu_Xingming,None
2206,2207.0,Jun,Zhuo,52,F,Hong Kong,1978,1.0,0.000,Manufacturing,Printed Circuit Boards,https://specials-images.forbesimg.com/imageser...,Jun_Zhuo,None
2207,2208.0,Olgun,Zorlu,54,M,Turkey,1978,1.0,NaN,Diversified,Diversified,https://specials-images.forbesimg.com/imageser...,Olgun_Zorlu,None

In [21]:
df.to_csv('df_file', index=False)